window.PAROLES_TEXTS = [
"Je ne suis pas la mais je peux vous lire.",
"Sombre merde.",
"C'est à proscrire.",
"Conseil des tas.",
"Faut réenchanter le wording.",
"GODI PRUNES du jardin.",
"Go pour l'actu !",
"Tarifaire pâté de foie de porc en boite de conserve.",
"Si la question n'est pas répondue ici.",
"Tu sais dans la vie, tout ressemble à une ro ?.",
"Il ne marche pas tout seul, il y a sa légende avec lui.",
"J'aime la douane, je chie pas (sauf devant sa porte).",
"Tu sais dans la vie, tout ressemble à une ro ?.",
"Tout est compliqué.",
"Je vais me bastonner à la piscine chaque semaine.",
"On y va à 3. Mais je croyais qu'on allait à Rouen.",
"Mi-chaffouin, mi-mossad.",
"Cancer de l'intélligence.",
"Sac à merde.",
];
